### ISSUE TITLE
날짜가 변경되었음을 알 수 있는 기능 요청

### ISSUE THREAD

**Issue by gwanhwi** [mijien0179/PCTORY#14]
**어떤 작업을 할 때 필요하나요?**

자정이 넘어가면서 날짜가 변경 되었을 때 자동으로 file log를 저장하기 위해 필요합니다.

**어떤 기능이 추가되길 바라나요?**

현재 날짜가 변경되었음을 알 수 있는 기능 요청합니다.
ex) 자정이 지나서 현재 날짜가 2022-05-19에서 2022-05-20으로 변경 되었음을 알 수 있는 기능

**Comment by mijien0179** [comment]
관련 기능이 Windows API에 존재하는지 판단 후, 존재하면 만들겠습니다.

**Comment by mijien0179** [comment]
Windows 메시지에는 존재하지 않는 것으로 판단되어, 따로 스레드 생성 후 날이 변경되었을 때 DayChanged 이벤트가 발생하도록 했습니다.

PR #26
