### ISSUE TITLE
시작 프로그램 등록 함수

### ISSUE THREAD

**Issue by mijien0179** [mijien0179/PCTORY#15]
**어떤 작업을 할 때 필요하나요?**
최종 릴리즈 시, 자동으로 실행해서 프로그램이 OS 시작과 함께 동작하도록 하는 기능이 필요함

**어떤 기능이 추가되길 바라나요?**
1. 시작 프로그램을 등록하는 함수
2. 등록된 시작 프로그램을 해제하는 함수

**Comment by gwanhwi** [comment]
기능 구현해서 Pull request했습니다
확인 부탁드려요
