### ISSUE TITLE
Windows 시작시 폼 보이지 않게 하는 코드 추가 필요

### ISSUE THREAD

**Issue by mijien0179** [mijien0179/PCTORY#23]
**어떤 작업을 할 때 필요하나요?**
Windows 시작 시, 메인 폼이 나오는 것은 좋지 못하다고 생각됨

**어떤 기능이 추가되길 바라나요?**
시작 argument에서 **--autorun**이 있는 경우, 폼을 숨기는 코드가 필요함

**Comment by jihong99** [comment]
Window 시작시 메인 폼이 아예 나오지 않고 프로그램이 autorun되는 것보다,
사용자가 프로그램 실행버튼을 눌렀을 때 프로그램이 시작되고 그 이후에 폼이 보이지 않게 하는 게 더 나을거같은데
의견 부탁드립니다.

**Comment by mijien0179** [comment]
> Window 시작시 메인 폼이 아예 나오지 않고 프로그램이 autorun되는 것보다, 사용자가 프로그램 실행버튼을 눌렀을 때 프로그램이 시작되고 그 이후에 폼이 보이지 않게 하는 게 더 나을거같은데 의견 부탁드립니다.

해당 방식으로 개발을 진행한다면, 자동 시작 기능의 존재 의의가 사라진다고 생각합니다. @jihong99

**Comment by jihong99** [comment]
> 
확인했습니다. 요청한 기능 추가하겠습니다.
