### ISSUE TITLE
인덱스 버그

### ISSUE THREAD

**Issue by mijien0179** [mijien0179/PCTORY#34]
https://github.com/mijien0179/PCTORY/blob/62e3a51d9243292983a222d01f568212fa93a9f4/pctory/Graph.cs#L94

해당 코드에서부터 인덱스에 따른 `OutOfRange` 문제가 발생하네요. 문제 수정 바랍니다.

**Comment by cacaocoffee** [comment]
#35 에서 수정했습니다! 확인 부탁드려요
