### ISSUE TITLE
그래프 필요 기능 구현 목록

### ISSUE THREAD

**Issue by cacaocoffee** [mijien0179/PCTORY#6]
데이터 불러오기, 저장양식 맞춰서 저장하기.

그래프 연동해서 일간, 주간, 월간 사용 그래프  자식 창 구현

**Comment by mijien0179** [comment]
그래프는 `사용 빈도수`, `사용시간` 등으로도 볼 수 있도록 구성하는 편이 좋을 것 같습니다.

**Comment by cacaocoffee** [comment]
> 
사용 빈도수 시간 둘다 확인할 수 있도록 하겠습니다.

**Comment by cacaocoffee** [comment]
사용 빈도 , 사용시간 탭으로 변경 필요.
사용수 상위 5개 노출 나머지는 기타로 분류해서 표기.

**Comment by cacaocoffee** [comment]
시간대 초,분,시 별로 자동 전환해서 나타내기
